# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161008120706 on 2016-10-16 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_logitem_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='md',
            field=models.TextField(max_length=50000),
        ),
    ]
