# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0004_auto_20161016_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitem',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='log_item', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
