# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_logitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='log_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
