# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0007_auto_20161031_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logitem',
            name='user',
        ),
        migrations.AddField(
            model_name='logitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
